apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-processor.fullname" . }}
  labels:
    {{- include "eks-processor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.targetPort | default "80" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eks-processor.selectorLabels" . | nindent 4 }}
