# values.yaml
repository: ${repository}
tag: ${tag}
replicas: ${replicas}
serviceAccountName: ${service_account_name}
serviceAccountRoleArn: ${service_account_role_arn}

# Environment variables
env:
  AWS_REGION: ${env_vars.AWS_REGION}
  ENVIRONMENT: ${env_vars.ENVIRONMENT}
  MODEL_NAME: ${env_vars.MODEL_NAME}
  DB_CLUSTER_ARN: ${env_vars.DB_CLUSTER_ARN}
  DB_SECRET_ARN: ${env_vars.DB_SECRET_ARN}
  DB_NAME: ${env_vars.DB_NAME}
  
# Resources
resources:
  limits:
    cpu: ${resources.limits.cpu}
    memory: ${resources.limits.memory}
  requests:
    cpu: ${resources.requests.cpu}
    memory: ${resources.requests.memory}
